### ISSUE TITLE
Negative state value display with 2 signs  '-'

### ISSUE THREAD

**Issue by grichka49** [AmoebeLabs/swiss-army-knife-card#162] opened 2022-08-17 19:08 UTC
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [X ] Yes, I'm sure that it is not a configuration mistake

## Bug description
Negative state value from entity is displaye with 2 signs '--'.
Example:  the value '-3' displays '--3'

### To Reproduce
Each time some negative state value should be displayed

### Expected behavior
Negative value should be displayed with only one sign "-"

### Screenshots
![image](https://user-images.githubusercontent.com/31791870/185221187-1051a750-564d-4f8b-970e-7440bd0902e6.png)

### Desktop browser (please complete the following information):
 - OS: Windows
 - Browser [Chrome ou Firefox]

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: [Poco F3]
 - OS: [Android 12]
 - Browser [Chrome]

**Additional context**

**Comment by AmoebeLabs** [comment] 2022-08-18 13:15
That looks like a regression.

Previously "0" was displayed as "-0". This was fixed, but obviously, some other bug was born 😨 

I will fix that in the next release!

**Comment by jwaz73** [comment] 2023-01-26 15:31
FYI, seeing the same behavior.

**Comment by jgatringer** [comment] 2023-01-27 07:25
Hello. seeing the same problem. Can this please will fixed?

**Comment by AmoebeLabs** [comment] 2023-04-30 09:11
Will be fixed in the May 2023 release!

**Closed** 2023-04-30 09:30 UTC
Labels: bug, tool/state
