### ISSUE TITLE
Negative numbers have disappeared

### ISSUE THREAD

**Issue by stgallazzi** [AmoebeLabs/swiss-army-knife-card#209] opened 2023-05-16 06:18 UTC
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [ ] Yes, I'm sure that it is not a configuration mistake

## Swiss Army Knife version
The version you are using. See HACS or the Browser console
Last version: v. 2.4.2

## Bug description
Negative numbers have disappeared and appear as positive numbers. In particular in the segmented arc tool, bat not only.

### To Reproduce
1.  Install new version of SAK

### Expected behavior
Display negative numbers

### Desktop browser (please complete the following information):
 - OS:  windows
 - Browser Firefox / Crome
![Screenshot](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/111341335/adbc9c8e-dd48-48d9-bd37-fbde80c9bd65)

**Comment by AmoebeLabs** [comment] 2023-05-16 07:04
That looks like a regression. Will be fixed in the next release.

BTW, before negative numbers had two '--' signs,, which was fixed, but obviously I made a mistake...

**Closed** 2023-05-16 08:55 UTC
Labels: bug, tool/state, bug/regression
